### ISSUE TITLE
Box on Lock screen time

### ISSUE THREAD

**Issue by shahriar-shojib** [Magisk-Modules-Repo/OnePlus-Slate-Font#1]
How do I fix the box on lock screen (screenshot attached)
![image](https://user-images.githubusercontent.com/6505094/34902349-f65ff0d4-f843-11e7-9a0c-f270ef288f86.png)

**Comment by SantiagoPintos** [comment]
Fixed :)

**Comment by hackel** [comment]
This is still happening to me with the latest version.
